const types={
  GET_SLIDERS:'GET_SLIDERS',
  GET_DETAIL_SLIDERS:'GET_DETAIL_SLIDERS',
  GET_HOT_PRODUCT:'GET_HOT_PRODUCT',
  GET_HOT_SHOPS:'GET_HOT_SHOPS',
  GET_PRODUCT:'GET_PRODUCT',
  GET_LIST_PRODUCT:'GET_LIST_PRODUCT'
}
export default types
